"""Added work experience skill table

Revision ID: 035427412e97
Revises: a700ba4ae9f2
Create Date: 2023-04-05 23:11:16.684302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035427412e97'
down_revision = 'a700ba4ae9f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_experience_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_experience_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.ForeignKeyConstraint(['work_experience_id'], ['work_experience.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_experience_skill')
    # ### end Alembic commands ###
