"""empty message

Revision ID: 0acf180e98fd
Revises: a475eb98c0a6
Create Date: 2023-03-31 20:16:37.810375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0acf180e98fd'
down_revision = 'a475eb98c0a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.alter_column('school_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('degree',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               nullable=True)

    with op.batch_alter_table('work_experience', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_experience', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('end_date',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('company_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('end_date',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('degree',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('school_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
