"""empty message

Revision ID: 899c2407b4f6
Revises: 6d4f6f8f989e
Create Date: 2023-04-05 15:04:37.825779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899c2407b4f6'
down_revision = '6d4f6f8f989e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('invitation_code_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invitation_code_id'], ['invitation_code.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    op.drop_table('invitation_code')
    # ### end Alembic commands ###
