"""empty message

Revision ID: 90fb5f4169b6
Revises: 365056be8d72
Create Date: 2023-03-31 20:01:24.748029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90fb5f4169b6'
down_revision = '365056be8d72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.drop_column('proficiency')

    with op.batch_alter_table('user_languages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proficiency', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_languages', schema=None) as batch_op:
        batch_op.drop_column('proficiency')

    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proficiency', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
