"""empty message

Revision ID: a475eb98c0a6
Revises: 90fb5f4169b6
Create Date: 2023-03-31 20:12:24.843329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a475eb98c0a6'
down_revision = '90fb5f4169b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_languages', schema=None) as batch_op:
        batch_op.alter_column('proficiency',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_languages', schema=None) as batch_op:
        batch_op.alter_column('proficiency',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
