"""Added profile links table

Revision ID: a700ba4ae9f2
Revises: f0756f8731bb
Create Date: 2023-04-05 19:10:16.895538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a700ba4ae9f2'
down_revision = 'f0756f8731bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('linkedin_url')
        batch_op.drop_column('github_url')
        batch_op.drop_column('website_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_url', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('github_url', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('linkedin_url', mysql.VARCHAR(length=255), nullable=True))

    op.drop_table('profile_links')
    # ### end Alembic commands ###
