"""empty message

Revision ID: dd0b18c65be9
Revises: 0500d58422d7
Create Date: 2023-03-30 13:18:06.830808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd0b18c65be9'
down_revision = '0500d58422d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.alter_column('soft_skill',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('hard_skill',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.alter_column('hard_skill',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('soft_skill',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    # ### end Alembic commands ###
