"""Addec location and currently_working to work_experience

Revision ID: 05afe5b5c699
Revises: 38dded99ff07
Create Date: 2023-04-06 21:38:03.598056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05afe5b5c699'
down_revision = '38dded99ff07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_experience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('currently_working', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_experience', schema=None) as batch_op:
        batch_op.drop_column('currently_working')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
