"""Renamed resume_contact_information_links to resume_contact_information_link

Revision ID: 31c9d2e07201
Revises: 405ff5e1e30c
Create Date: 2023-04-10 19:30:27.959724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '31c9d2e07201'
down_revision = '405ff5e1e30c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_contact_information_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_contact_information_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['resume_contact_information_id'], ['resume_contact_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('resume_contact_information_links')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_contact_information_links',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('resume_contact_information_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['resume_contact_information_id'], ['resume_contact_information.id'], name='resume_contact_information_links_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('resume_contact_information_link')
    # ### end Alembic commands ###
