"""Added location, major_or_area_of_study, and currently_attending to education

Revision ID: 33bbd2484781
Revises: 05afe5b5c699
Create Date: 2023-04-06 22:20:07.636315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33bbd2484781'
down_revision = '05afe5b5c699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('major_or_area_of_study', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('currently_attending', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.drop_column('currently_attending')
        batch_op.drop_column('major_or_area_of_study')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
