"""Fixed pluralization of tables

Revision ID: 38dded99ff07
Revises: 035427412e97
Create Date: 2023-04-06 19:21:00.222200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38dded99ff07'
down_revision = '035427412e97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('proficiency', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_posting_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_posting.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('job_posting_skills')
    op.drop_table('profile_skills')
    op.drop_table('profile_languages')
    op.drop_table('profile_links')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_links',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name='profile_links_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('profile_languages',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('language_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proficiency', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], name='profile_languages_ibfk_1'),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name='profile_languages_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('profile_skills',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name='profile_skills_ibfk_1'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name='profile_skills_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('job_posting_skills',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_posting_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_posting.id'], name='job_posting_skills_ibfk_1'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name='job_posting_skills_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('job_posting_skill')
    op.drop_table('profile_skill')
    op.drop_table('profile_link')
    op.drop_table('profile_language')
    # ### end Alembic commands ###
