"""Change job_posting to have account_id instead of profile_id

Revision ID: 405ff5e1e30c
Revises: 76361fd50bac
Create Date: 2023-04-08 18:33:42.433624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '405ff5e1e30c'
down_revision = '76361fd50bac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'account', ['account_id'], ['id'])
        batch_op.drop_column('profile_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
