"""Fixed resume_project table

Revision ID: 76361fd50bac
Revises: b52cb6f52bad
Create Date: 2023-04-08 16:09:02.188541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76361fd50bac'
down_revision = 'b52cb6f52bad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('resume_project_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'resume', ['resume_id'], ['id'])
        batch_op.drop_column('resume_work_experience_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_work_experience_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('resume_project_ibfk_1', 'resume_work_experience', ['resume_work_experience_id'], ['id'])
        batch_op.drop_column('resume_id')

    # ### end Alembic commands ###
