name: Python linting and tests

on:
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - 'jobpilot_back/**'

permissions:
  contents: read

defaults:
  run:
    working-directory: jobpilot_back

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install requirements
      run: |
        pip install flake8 pytest
    - name: Lint with flake8
      run: |
        flake8 . --count --statistics
    - name: Run tests
      run: |
        python -m pytest
